// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zBangumiIntro = z.object({
    animeId: z.number().int().optional(),
    bangumiId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    animeTitle: z.union([
        z.string(),
        z.null()
    ]).optional(),
    imageUrl: z.union([
        z.string(),
        z.null()
    ]).optional(),
    searchKeyword: z.union([
        z.string(),
        z.null()
    ]).optional(),
    isOnAir: z.boolean().optional(),
    airDay: z.number().int().optional(),
    isFavorited: z.boolean().optional(),
    isRestricted: z.boolean().optional(),
    rating: z.number().optional()
});

export const zResponseBase = z.object({
    errorCode: z.number().int().optional(),
    success: z.boolean().optional(),
    errorMessage: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zBangumiListResponse = zResponseBase.and(z.object({
    bangumiList: z.union([
        z.array(zBangumiIntro),
        z.null()
    ]).optional()
}));

export const zBangumiSeason = z.object({
    year: z.number().int().optional(),
    month: z.number().int().optional(),
    seasonName: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zBangumiSeasonListResponse = zResponseBase.and(z.object({
    seasons: z.union([
        z.array(zBangumiSeason),
        z.null()
    ]).optional()
}));

export const zBangumiQueueIntroV2 = z.object({
    animeId: z.number().int().optional(),
    animeTitle: z.union([
        z.string(),
        z.null()
    ]).optional(),
    episodeTitle: z.union([
        z.string(),
        z.null()
    ]).optional(),
    airDate: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    imageUrl: z.union([
        z.string(),
        z.null()
    ]).optional(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    isOnAir: z.boolean().optional()
});

export const zBangumiQueueIntroResponseV2 = zResponseBase.and(z.object({
    hasMore: z.boolean().optional(),
    bangumiList: z.union([
        z.array(zBangumiQueueIntroV2),
        z.null()
    ]).optional()
}));

export const zBangumiQueueEpisodeV2 = z.object({
    episodeId: z.coerce.bigint().optional(),
    episodeTitle: z.union([
        z.string(),
        z.null()
    ]).optional(),
    airDate: z.union([
        z.string().datetime(),
        z.null()
    ]).optional()
});

export const zBangumiQueueDetailsV2 = z.object({
    animeId: z.number().int().optional(),
    animeTitle: z.union([
        z.string(),
        z.null()
    ]).optional(),
    isOnAir: z.boolean().optional(),
    imageUrl: z.union([
        z.string(),
        z.null()
    ]).optional(),
    searchKeyword: z.union([
        z.string(),
        z.null()
    ]).optional(),
    lastWatched: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    episodes: z.union([
        z.array(zBangumiQueueEpisodeV2),
        z.null()
    ]).optional()
});

export const zBangumiQueueDetailsResponseV2 = zResponseBase.and(z.object({
    bangumiList: z.union([
        z.array(zBangumiQueueDetailsV2),
        z.null()
    ]).optional(),
    unwatchedBangumiList: z.union([
        z.array(zBangumiQueueDetailsV2),
        z.null()
    ]).optional()
}));

export const zAnimeType = z.enum([
    'tvseries',
    'tvspecial',
    'ova',
    'movie',
    'musicvideo',
    'web',
    'other',
    'jpmovie',
    'jpdrama',
    'unknown',
    'tmdbtv',
    'tmdbmovie'
]);

export const zBangumiTitle = z.object({
    language: z.union([
        z.string(),
        z.null()
    ]).optional(),
    title: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zBangumiEpisodeSeason = z.object({
    id: z.union([
        z.string(),
        z.null()
    ]).optional(),
    airDate: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    episodeCount: z.number().int().optional(),
    summary: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zBangumiEpisode = z.object({
    seasonId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    episodeId: z.coerce.bigint().optional(),
    episodeTitle: z.union([
        z.string(),
        z.null()
    ]).optional(),
    episodeNumber: z.union([
        z.string(),
        z.null()
    ]).optional(),
    lastWatched: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    airDate: z.union([
        z.string().datetime(),
        z.null()
    ]).optional()
});

export const zFavoriteStatus = z.enum([
    'favorited',
    'finished',
    'abandoned'
]);

export const zBangumiTag = z.object({
    id: z.number().int().optional(),
    name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    count: z.number().int().optional()
});

export const zBangumiOnlineDatabase = z.object({
    name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    url: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zBangumiTrailer = z.object({
    id: z.number().int().optional(),
    url: z.union([
        z.string(),
        z.null()
    ]).optional(),
    title: z.union([
        z.string(),
        z.null()
    ]).optional(),
    imageUrl: z.union([
        z.string(),
        z.null()
    ]).optional(),
    date: z.string().datetime().optional()
});

export const zBangumiDetails = zBangumiIntro.and(z.object({
    type: zAnimeType.optional(),
    typeDescription: z.union([
        z.string(),
        z.null()
    ]).optional(),
    titles: z.union([
        z.array(zBangumiTitle),
        z.null()
    ]).optional(),
    seasons: z.union([
        z.array(zBangumiEpisodeSeason),
        z.null()
    ]).optional(),
    episodes: z.union([
        z.array(zBangumiEpisode),
        z.null()
    ]).optional(),
    summary: z.union([
        z.string(),
        z.null()
    ]).optional(),
    intro: z.union([
        z.string(),
        z.null()
    ]).optional(),
    metadata: z.union([
        z.array(z.string()),
        z.null()
    ]).optional(),
    bangumiUrl: z.union([
        z.string(),
        z.null()
    ]).optional(),
    userRating: z.number().int().optional(),
    favoriteStatus: z.union([
        zFavoriteStatus,
        z.null()
    ]).optional(),
    comment: z.union([
        z.string(),
        z.null()
    ]).optional(),
    ratingDetails: z.union([
        z.record(z.number()),
        z.null()
    ]).optional(),
    relateds: z.union([
        z.array(zBangumiIntro),
        z.null()
    ]).optional(),
    similars: z.union([
        z.array(zBangumiIntro),
        z.null()
    ]).optional(),
    tags: z.union([
        z.array(zBangumiTag),
        z.null()
    ]).optional(),
    onlineDatabases: z.union([
        z.array(zBangumiOnlineDatabase),
        z.null()
    ]).optional(),
    trailers: z.union([
        z.array(zBangumiTrailer),
        z.null()
    ]).optional()
}));

export const zBangumiDetailsResponse = zResponseBase.and(z.object({
    bangumi: z.union([
        zBangumiDetails,
        z.null()
    ]).optional()
}));

export const zCommentData = z.object({
    cid: z.coerce.bigint().optional(),
    p: z.union([
        z.string(),
        z.null()
    ]).optional(),
    m: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * 弹幕列表
 */
export const zCommentResponseV2 = z.object({
    count: z.number().int().optional(),
    comments: z.union([
        z.array(zCommentData),
        z.null()
    ]).optional()
});

export const zSendCommentResponseV2 = zResponseBase.and(z.object({
    cid: z.coerce.bigint().optional()
}));

export const zSendCommentRequest = z.object({
    time: z.number().optional(),
    mode: z.number().int().optional(),
    color: z.number().int().optional(),
    comment: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zUserFavoriteItem = z.object({
    animeId: z.number().int().optional(),
    bangumiId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    animeTitle: z.union([
        z.string(),
        z.null()
    ]).optional(),
    type: zAnimeType.optional(),
    lastFavoriteTime: z.string().datetime().optional(),
    lastAirDate: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    lastWatchTime: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    imageUrl: z.union([
        z.string(),
        z.null()
    ]).optional(),
    episodeTotal: z.number().int().optional(),
    episodeWatched: z.number().int().optional(),
    startDate: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    isOnAir: z.boolean().optional(),
    favoriteStatus: zFavoriteStatus.optional(),
    userRating: z.number().int().optional(),
    rating: z.number().optional()
});

export const zUserFavoriteResponse = zResponseBase.and(z.object({
    favorites: z.union([
        z.array(zUserFavoriteItem),
        z.null()
    ]).optional()
}));

export const zUserAddFavoriteResponse = zResponseBase.and(z.object({}));

export const zUserAddFavoriteRequest = z.object({
    animeId: z.number().int().optional(),
    favoriteStatus: z.union([
        zFavoriteStatus,
        z.null()
    ]).optional(),
    rating: z.number().int().optional(),
    comment: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zUserDeleteFavoriteResponse = zResponseBase.and(z.object({}));

export const zBannerPageItem = z.object({
    id: z.number().int().optional(),
    title: z.union([
        z.string(),
        z.null()
    ]).optional(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    url: z.union([
        z.string(),
        z.null()
    ]).optional(),
    imageUrl: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zHomepageResponseV2 = zResponseBase.and(z.object({
    banners: z.union([
        z.array(zBannerPageItem),
        z.null()
    ]).optional(),
    bangumiQueueIntroList: z.union([
        z.array(zBangumiQueueIntroV2),
        z.null()
    ]).optional(),
    shinBangumiList: z.union([
        z.array(zBangumiIntro),
        z.null()
    ]).optional(),
    bangumiSeasons: z.union([
        z.array(zBangumiSeason),
        z.null()
    ]).optional()
}));

export const zBannerResponse = zResponseBase.and(z.object({
    banners: z.union([
        z.array(zBannerPageItem),
        z.null()
    ]).optional()
}));

export const zPayConfigItem = z.object({
    id: z.union([
        z.string(),
        z.null()
    ]).optional(),
    name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    price: z.number().int().optional(),
    currency: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zPayConfig = z.object({
    providerId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    providerName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    items: z.union([
        z.array(zPayConfigItem),
        z.null()
    ]).optional()
});

/**
 * 用户各类权益到期时间
 */
export const zUserPrivileges = z.object({
    member: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    resmonitor: z.union([
        z.string().datetime(),
        z.null()
    ]).optional()
});

export const zLoginResponse = zResponseBase.and(z.object({
    registerRequired: z.boolean().optional(),
    userId: z.number().int().optional(),
    userName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    legacyTokenNumber: z.number().int().optional(),
    token: z.union([
        z.string(),
        z.null()
    ]).optional(),
    tokenExpireTime: z.string().datetime().optional(),
    userType: z.union([
        z.string(),
        z.null()
    ]).optional(),
    screenName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    profileImage: z.union([
        z.string(),
        z.null()
    ]).optional(),
    appScope: z.union([
        z.string(),
        z.null()
    ]).optional(),
    payConfigs: z.union([
        z.array(zPayConfig),
        z.null()
    ]).optional(),
    privileges: z.union([
        zUserPrivileges,
        z.null()
    ]).optional(),
    code: z.union([
        z.string(),
        z.null()
    ]).optional(),
    ts: z.coerce.bigint().optional()
}));

/**
 * 请求用户登录
 */
export const zLoginRequest = z.object({
    userName: z.string().min(0).max(50),
    password: z.string().min(0).max(50),
    appId: z.string().min(0).max(20),
    unixTimestamp: z.coerce.bigint().gte(BigInt(1)).lte(BigInt(9223372036854780000)).optional(),
    hash: z.string().min(1).regex(/^[0-9a-fA-F]{32}$/)
});

export const zMatchResultV2 = z.object({
    episodeId: z.coerce.bigint().optional(),
    animeId: z.number().int().optional(),
    animeTitle: z.union([
        z.string(),
        z.null()
    ]).optional(),
    episodeTitle: z.union([
        z.string(),
        z.null()
    ]).optional(),
    type: zAnimeType.optional(),
    typeDescription: z.union([
        z.string(),
        z.null()
    ]).optional(),
    shift: z.number().optional(),
    imageUrl: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zMatchResponseV2 = zResponseBase.and(z.object({
    isMatched: z.boolean().optional(),
    matches: z.union([
        z.array(zMatchResultV2),
        z.null()
    ]).optional()
}));

export const zMatchMode = z.enum([
    'hashAndFileName',
    'fileNameOnly',
    'hashOnly'
]);

export const zMatchRequest = z.object({
    fileName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    fileHash: z.union([
        z.string(),
        z.null()
    ]).optional(),
    fileSize: z.coerce.bigint().optional(),
    videoDuration: z.number().int().optional(),
    matchMode: zMatchMode.optional()
});

export const zBatchMatchResponseItem = z.object({
    success: z.boolean().optional(),
    fileHash: z.union([
        z.string(),
        z.null()
    ]).optional(),
    matchResult: z.union([
        zMatchResultV2,
        z.null()
    ]).optional()
});

export const zBatchMatchResponse = zResponseBase.and(z.object({
    results: z.union([
        z.array(zBatchMatchResponseItem),
        z.null()
    ]).optional()
}));

/**
 * 批量匹配的请求
 */
export const zBatchMatchRequest = z.object({
    requests: z.union([
        z.array(zMatchRequest),
        z.null()
    ]).optional()
});

export const zUserPlayHistoryAnime = z.object({
    animeId: z.number().int().optional(),
    animeTitle: z.union([
        z.string(),
        z.null()
    ]).optional(),
    type: zAnimeType.optional(),
    typeDescription: z.union([
        z.string(),
        z.null()
    ]).optional(),
    imageUrl: z.union([
        z.string(),
        z.null()
    ]).optional(),
    isOnAir: z.boolean().optional(),
    episodes: z.union([
        z.array(zBangumiEpisode),
        z.null()
    ]).optional()
});

export const zUserPlayHistoryResponse = zResponseBase.and(z.object({
    playHistoryAnimes: z.union([
        z.array(zUserPlayHistoryAnime),
        z.null()
    ]).optional()
}));

export const zUserAddPlayHistoryResponse = zResponseBase.and(z.object({}));

export const zUserAddPlayHistoryRequest = z.object({
    episodeIdList: z.union([
        z.array(z.coerce.bigint()),
        z.null()
    ]).optional(),
    addToFavorite: z.boolean().optional(),
    rating: z.number().int().optional()
});

export const zRegisterRequestV2 = z.object({
    appId: z.string().min(1),
    userName: z.string().min(1),
    password: z.string().min(1),
    email: z.string().min(1),
    screenName: z.string().min(1),
    unixTimestamp: z.coerce.bigint().gte(BigInt(1)).lte(BigInt(9223372036854780000)).optional(),
    hash: z.string().min(1).regex(/^[0-9a-fA-F]{32}$/)
});

export const zResetPasswordResponseV2 = zResponseBase.and(z.object({}));

export const zResetPasswordRequestV2 = z.object({
    appId: z.string().min(1),
    userName: z.string().min(5).max(20),
    email: z.string().min(1),
    unixTimestamp: z.coerce.bigint().gte(BigInt(1)).lte(BigInt(9223372036854780000)).optional(),
    hash: z.string().min(1).regex(/^[0-9a-fA-F]{32}$/)
});

export const zFindMyIdResponse = zResponseBase.and(z.object({}));

export const zFindMyIdRequestV2 = z.object({
    appId: z.string().min(1).max(20),
    email: z.string().min(1).max(50),
    unixTimestamp: z.coerce.bigint().gte(BigInt(1)).lte(BigInt(9223372036854780000)).optional(),
    hash: z.string().min(1).regex(/^[0-9a-fA-F]{32}$/)
});

export const zRelatedItemV2 = z.object({
    url: z.union([
        z.string(),
        z.null()
    ]).optional(),
    shift: z.number().optional()
});

export const zRelatedResponseV2 = zResponseBase.and(z.object({
    relateds: z.union([
        z.array(zRelatedItemV2),
        z.null()
    ]).optional()
}));

export const zUserAddRelatedResponse = zResponseBase.and(z.object({}));

export const zUserAddRelatedRequest = z.object({
    episodeId: z.coerce.bigint().optional(),
    url: z.union([
        z.string(),
        z.null()
    ]).optional(),
    shift: z.number().optional()
});

export const zUserDeleteRelatedResponse = zResponseBase.and(z.object({}));

export const zSearchAnimeDetails = z.object({
    animeId: z.number().int().optional(),
    bangumiId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    animeTitle: z.union([
        z.string(),
        z.null()
    ]).optional(),
    type: zAnimeType.optional(),
    typeDescription: z.union([
        z.string(),
        z.null()
    ]).optional(),
    imageUrl: z.union([
        z.string(),
        z.null()
    ]).optional(),
    startDate: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    episodeCount: z.number().int().optional(),
    rating: z.number().optional(),
    isFavorited: z.boolean().optional()
});

export const zSearchAnimeResponse = zResponseBase.and(z.object({
    animes: z.union([
        z.array(zSearchAnimeDetails),
        z.null()
    ]).optional()
}));

export const zSearchEpisodeDetails = z.object({
    episodeId: z.coerce.bigint().optional(),
    episodeTitle: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zSearchEpisodesAnime = z.object({
    animeId: z.number().int().optional(),
    animeTitle: z.union([
        z.string(),
        z.null()
    ]).optional(),
    type: zAnimeType.optional(),
    typeDescription: z.union([
        z.string(),
        z.null()
    ]).optional(),
    episodes: z.union([
        z.array(zSearchEpisodeDetails),
        z.null()
    ]).optional()
});

export const zSearchEpisodesResponse = zResponseBase.and(z.object({
    hasMore: z.boolean().optional(),
    animes: z.union([
        z.array(zSearchEpisodesAnime),
        z.null()
    ]).optional()
}));

export const zSearchBangumiDetails = zSearchAnimeDetails.and(z.object({
    rank: z.number().int().optional(),
    searchKeyword: z.union([
        z.string(),
        z.null()
    ]).optional(),
    isOnAir: z.boolean().optional(),
    isRestricted: z.boolean().optional(),
    intro: z.union([
        z.string(),
        z.null()
    ]).optional()
}));

export const zSearchBangumiResponse = zResponseBase.and(z.object({
    bangumis: z.union([
        z.array(zSearchBangumiDetails),
        z.null()
    ]).optional()
}));

export const zConfigKey = z.object({
    key: z.number().int().optional(),
    value: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zSearchAdvancedConfigResponse = zResponseBase.and(z.object({
    types: z.union([
        z.array(zConfigKey),
        z.null()
    ]).optional(),
    tags: z.union([
        z.array(zConfigKey),
        z.null()
    ]).optional(),
    sorts: z.union([
        z.array(zConfigKey),
        z.null()
    ]).optional(),
    minYear: z.number().int().optional(),
    maxYear: z.number().int().optional()
}));

export const zUserUpdateProfileResponseV2 = zResponseBase.and(z.object({
    updateScreenName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    updateProfileImage: z.union([
        z.string(),
        z.null()
    ]).optional()
}));

export const zUserUpdatePasswordRequest = z.object({
    oldPassword: z.string().min(5).max(20),
    newPassword: z.string().min(5).max(20)
});

export const zUserUpdateProfileRequest = z.object({
    screenName: z.union([
        z.string().min(0).max(50),
        z.null()
    ]).optional(),
    profileImageBase64: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zUserUpdateEmailRequest = z.object({
    oldEmail: z.string().min(1),
    newEmail: z.string().min(1)
});

export const zBangumiGetShinBangumiData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        filterAdultContent: z.boolean().optional().default(false)
    }).optional()
});

export const zBangumiGetShinBangumiResponse = zBangumiListResponse;

export const zBangumiGetSeasonBangumiOfAnimeData = z.object({
    body: z.never().optional(),
    path: z.object({
        year: z.number().int(),
        month: z.number().int()
    }),
    query: z.object({
        filterAdultContent: z.boolean().optional().default(false)
    }).optional()
});

export const zBangumiGetSeasonBangumiOfAnimeResponse = zBangumiListResponse;

export const zBangumiGetSeasonsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zBangumiGetSeasonsResponse = zBangumiSeasonListResponse;

export const zBangumiGetQueueIntroData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zBangumiGetQueueIntroResponse = zBangumiQueueIntroResponseV2;

export const zBangumiGetQueueDetailsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zBangumiGetQueueDetailsResponse = zBangumiQueueDetailsResponseV2;

export const zBangumiGetBangumiDetailsData = z.object({
    body: z.never().optional(),
    path: z.object({
        bangumiId: z.string()
    }),
    query: z.never().optional()
});

export const zBangumiGetBangumiDetailsResponse = zBangumiDetailsResponse;

export const zBangumiGetBangumiDetailsByBgmtvSubjectIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        bgmtvSubjectId: z.number().int()
    }),
    query: z.never().optional()
});

export const zBangumiGetBangumiDetailsByBgmtvSubjectIdResponse = zBangumiDetailsResponse;

export const zCommentGetCommentData = z.object({
    body: z.never().optional(),
    path: z.object({
        episodeId: z.coerce.bigint()
    }),
    query: z.object({
        from: z.coerce.bigint().optional().default(BigInt(0)),
        withRelated: z.boolean().optional().default(false),
        chConvert: z.number().int().optional().default(0)
    }).optional()
});

export const zCommentSendCommentData = z.object({
    body: zSendCommentRequest,
    path: z.object({
        episodeId: z.coerce.bigint()
    }),
    query: z.never().optional()
});

/**
 * 返回发送弹幕的结果
 */
export const zCommentSendCommentResponse = zSendCommentResponseV2;

export const zCommentGetExtCommentData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        url: z.string().optional(),
        chConvert: z.number().int().optional().default(0)
    }).optional()
});

export const zFavoriteGetUserFavoriteData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        onlyOnAir: z.boolean().optional().default(false)
    }).optional()
});

/**
 * 返回用户关注的作品列表
 */
export const zFavoriteGetUserFavoriteResponse = zUserFavoriteResponse;

export const zFavoriteAddFavoriteData = z.object({
    body: zUserAddFavoriteRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * 返回添加关注的结果
 */
export const zFavoriteAddFavoriteResponse = zUserAddFavoriteResponse;

export const zFavoriteDeleteFavoriteData = z.object({
    body: z.never().optional(),
    path: z.object({
        animeId: z.number().int()
    }),
    query: z.never().optional()
});

/**
 * 返回取消关注的结果
 */
export const zFavoriteDeleteFavoriteResponse = zUserDeleteFavoriteResponse;

export const zHomepageGetHomepageData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        filterAdultContent: z.boolean().optional().default(false)
    }).optional()
});

export const zHomepageGetHomepageResponse = zHomepageResponseV2;

export const zHomepageGetBannerData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zHomepageGetBannerResponse = zBannerResponse;

export const zLoginLoginData = z.object({
    body: zLoginRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zLoginLoginResponse = zLoginResponse;

export const zLoginRenewTokenData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * 返回Token刷新后的用户信息
 */
export const zLoginRenewTokenResponse = zLoginResponse;

export const zMatchMatchData = z.object({
    body: zMatchRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zMatchMatchResponse = zMatchResponseV2;

export const zMatchBatchMatchData = z.object({
    body: zBatchMatchRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zMatchBatchMatchResponse = zBatchMatchResponse;

export const zPlayHistoryGetUserPlayHistoryData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        fromDate: z.union([
            z.string().datetime(),
            z.null()
        ]).optional(),
        toDate: z.union([
            z.string().datetime(),
            z.null()
        ]).optional()
    }).optional()
});

/**
 * 返回用户播放历史
 */
export const zPlayHistoryGetUserPlayHistoryResponse = zUserPlayHistoryResponse;

export const zPlayHistoryAddPlayHistoryData = z.object({
    body: zUserAddPlayHistoryRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * 返回播放历史添加结果
 */
export const zPlayHistoryAddPlayHistoryResponse = zUserAddPlayHistoryResponse;

export const zRegisterRegisterMainUserData = z.object({
    body: zRegisterRequestV2,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zRegisterRegisterMainUserResponse = zLoginResponse;

export const zRegisterResetPasswordData = z.object({
    body: zResetPasswordRequestV2,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zRegisterResetPasswordResponse = zResetPasswordResponseV2;

export const zRegisterFindMyIdData = z.object({
    body: zFindMyIdRequestV2,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zRegisterFindMyIdResponse = zFindMyIdResponse;

export const zRelatedDeleteRelatedData = z.object({
    body: z.never().optional(),
    path: z.object({
        episodeId: z.coerce.bigint()
    }),
    query: z.object({
        url: z.string().optional()
    }).optional()
});

/**
 * 返回投票结果
 */
export const zRelatedDeleteRelatedResponse = zUserDeleteRelatedResponse;

export const zRelatedGetRelatedData = z.object({
    body: z.never().optional(),
    path: z.object({
        episodeId: z.coerce.bigint()
    }),
    query: z.never().optional()
});

export const zRelatedGetRelatedResponse = zRelatedResponseV2;

export const zRelatedAddRelatedData = z.object({
    body: zUserAddRelatedRequest,
    path: z.object({
        episodeId: z.coerce.bigint()
    }),
    query: z.never().optional()
});

/**
 * 返回投票结果
 */
export const zRelatedAddRelatedResponse = zUserAddRelatedResponse;

export const zSearchSearchAnimeData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        keyword: z.string().optional(),
        type: z.union([
            zAnimeType,
            z.null()
        ]).optional()
    }).optional()
});

export const zSearchSearchAnimeResponse = zSearchAnimeResponse;

export const zSearchSearchTmdbData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        keyword: z.string().optional()
    }).optional()
});

export const zSearchSearchTmdbResponse = zSearchAnimeResponse;

export const zSearchSearchEpisodesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        anime: z.union([
            z.string(),
            z.null()
        ]).optional(),
        tmdbId: z.union([
            z.number().int(),
            z.null()
        ]).optional(),
        episode: z.union([
            z.string(),
            z.null()
        ]).optional()
    }).optional()
});

export const zSearchSearchEpisodesResponse = zSearchEpisodesResponse;

export const zSearchSearchAnimeByTagData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        tags: z.string().optional()
    }).optional()
});

export const zSearchSearchAnimeByTagResponse = zSearchBangumiResponse;

export const zSearchGetSearchAdvConfigData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        source: z.union([
            z.string().default('anidb'),
            z.null()
        ]).optional().default('anidb')
    }).optional()
});

export const zSearchGetSearchAdvConfigResponse = zSearchAdvancedConfigResponse;

export const zSearchSearchAdvancedData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        source: z.union([
            z.string().default('anidb'),
            z.null()
        ]).optional().default('anidb'),
        keyword: z.union([
            z.string(),
            z.null()
        ]).optional(),
        type: z.union([
            z.number().int(),
            z.null()
        ]).optional(),
        tags: z.union([
            z.string(),
            z.null()
        ]).optional(),
        year: z.union([
            z.number().int(),
            z.null()
        ]).optional(),
        month: z.union([
            z.number().int(),
            z.null()
        ]).optional(),
        minRate: z.number().int().optional().default(0),
        maxRate: z.number().int().optional().default(10),
        restricted: z.union([
            z.boolean(),
            z.null()
        ]).optional(),
        sort: z.number().int().optional().default(0)
    }).optional()
});

export const zSearchSearchAdvancedResponse = zSearchBangumiResponse;

export const zUserUpdatePasswordData = z.object({
    body: zUserUpdatePasswordRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * 修改密码结果
 */
export const zUserUpdatePasswordResponse = zUserUpdateProfileResponseV2;

export const zUserUpdateProfileData = z.object({
    body: zUserUpdateProfileRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * 返回修改结果
 */
export const zUserUpdateProfileResponse = zUserUpdateProfileResponseV2;

export const zUserUpdateUserEmailData = z.object({
    body: zUserUpdateEmailRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * 修改邮箱结果
 */
export const zUserUpdateUserEmailResponse = zUserUpdateProfileResponseV2;
