packages:
  - 'packages/**'
  - 'backend/**'
  - 'app/**'
nodeLinker: isolated
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: false
  lefthook: false
  lmdb: false
  msgpackr-extract: false
  protobufjs: false
  sharp: false
  spawn-sync: false
  workerd: false
minimumReleaseAgeExclude:
  - '@mr-quin/dango-manifests@0.1.0'
  - '@mr-quin/dango@0.1.0'
