// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	ALLOWED_ORIGIN: string;
	DANDANPLAY_APP_ID: string;
	DANDANPLAY_APP_SECRET: string;
	DANDANPLAY_API_HOST: string;
	BASE_URL: string;
}
