// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
  DANDANPLAY_API_HOST: 'https://api.dandanplay.net'
  BASE_URL: '/proxy'
  ALLOWED_ORIGIN: string
  DANDANPLAY_APP_ID: string
  DANDANPLAY_APP_SECRET: string
}
